name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]' # Ensure this condition is valid and properly placed
    runs-on: ubuntu-latest

    steps:
      - name: Print PR Information
        run: echo "Actor: B"

      - name: Check PR Title for Minor or Patch
        id: check_update_type
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ (minor|patch) ]]; then
            echo "should_merge=true" >> $GITHUB_ENV
          else
            echo "should_merge=false" >> $GITHUB_ENV

      - name: Merge Pull Request
        if: env.should_merge == 'true' # Ensure this is properly indented and aligned
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash",
            })
