name: Auto Merge Dependabot PRs to Develop

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'binon'

    steps:
      - name: Wait for CI workflow to pass (Ensure CI workflow succeeded)
        id: wait_for_ci
        run: |
          # Triggered after CI workflow completes, check if it's successful
          PR_NUMBER=${{ github.event.pull_request.number }}
          
          # Fetch the latest commit status to ensure CI passed before proceeding with merge
          CI_STATUS=$(gh pr view $PR_NUMBER --json status --jq '.status')

          if [[ "$CI_STATUS" != "SUCCESS" ]]; then
            echo "CI failed, aborting merge."
            exit 1
          fi
      - name: Check Target Branch and PR Title
        id: check_branch
        run: |
          PR_TITLE='${{ github.event.pull_request.title }}'
          echo "Original PR Title: $PR_TITLE"
          
          # Escape problematic quotes
          ESCAPED_TITLE=$(echo "$PR_TITLE" | sed 's/"/\\"/g')
          echo "Escaped PR Title: $ESCAPED_TITLE"

          if [[ "$ESCAPED_TITLE" =~ ([0-9]+\.[0-9]+\.[0-9]+).*to.*([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            # Extract version numbers
            OLD_VERSION="${BASH_REMATCH[1]}"
            NEW_VERSION="${BASH_REMATCH[2]}"
            echo "Version change detected: $OLD_VERSION to $NEW_VERSION"
            
            # Split version into major, minor, patch components
            OLD_MAJOR=$(echo "$OLD_VERSION" | cut -d '.' -f1)
            OLD_MINOR=$(echo "$OLD_VERSION" | cut -d '.' -f2)
            OLD_PATCH=$(echo "$OLD_VERSION" | cut -d '.' -f3)
            
            NEW_MAJOR=$(echo "$NEW_VERSION" | cut -d '.' -f1)
            NEW_MINOR=$(echo "$NEW_VERSION" | cut -d '.' -f2)
            NEW_PATCH=$(echo "$NEW_VERSION" | cut -d '.' -f3)
            
            # Check if it's a minor or patch update
            if [[ "$OLD_MAJOR" == "$NEW_MAJOR" ]] && [[ "$OLD_MINOR" == "$NEW_MINOR" ]] && [[ "$NEW_PATCH" -gt "$OLD_PATCH" ]]; then
              echo "Patch update detected"
              echo "should_merge=true" >> $GITHUB_ENV
            elif [[ "$OLD_MAJOR" == "$NEW_MAJOR" ]] && [[ "$NEW_MINOR" -gt "$OLD_MINOR" ]]; then
              echo "Minor update detected"
              echo "should_merge=true" >> $GITHUB_ENV
            else
              echo "No minor/patch update detected"
              echo "should_merge=false" >> $GITHUB_ENV
            fi
          else
            echo "No version change detected"
            echo "should_merge=false" >> $GITHUB_ENV
          fi

      - name: Debug Context
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Target branch:", context.payload.pull_request.base.ref);

      - name: Check if Should Merge
        run: |
          echo "DEBUG: should_merge=${{ env.should_merge }}"
          if [[ "${{ env.should_merge }}" == "true" ]] && [[ "${{ github.event.pull_request.base.ref }}" == "master" ]]; then
            echo "DEBUG: should merge PR"
            echo "should_merge=true" >> $GITHUB_ENV
          else
            echo "DEBUG: skip merge"
            echo "should_merge=false" >> $GITHUB_ENV
          fi

      - name: Merge Pull Request
        if: ${{ env.should_merge == 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            });
