name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - closed
      - synchronize
      - reopened
      - opened

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: windows-latest

    steps:
      - name: Check PR Title for Minor or Patch
        id: check_update_type
        run: |
          echo "PR title: ${{ github.event.pull_request.title }}"
          if (( "${{ github.event.pull_request.title }}" =~ (minor|patch) )); then
            echo "should_merge=true" >> $GITHUB_ENV
          else
            echo "should_merge=false" >> $GITHUB_ENV

      - name: Check CI Status
        if: env.should_merge == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: checkRuns } = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });
            if (!checkRuns.check_runs.every(check => check.conclusion === "success")) {
              throw new Error("CI checks failed");
            }         

      - name: Merge Pull Request
        if: env.should_merge == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash",
            });
