name: Auto Merge Dependabot PRs to Develop

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'binon'

    steps:
      - name: Check Target Branch
        id: check_branch
        run: |
          PR_TITLE='${{ github.event.pull_request.title }}'
          # Escape problematic quotes
          ESCAPED_TITLE=$(echo "$PR_TITLE" | sed 's/"/\\"/g')
          console.log("ESCAPED TITLE:", ESCAPED_TITLE);
          
          if [[ "${{ github.event.pull_request.base.ref }}" == "master" ]] && [[ "$ESCAPED_TITLE" =~ (minor|patch) ]]; then
          else
            echo "should_merge=false" >> $GITHUB_ENV
          fi
          
      - name: Debug Context
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Target branch:", context.payload.pull_request.base.ref);

      - name: Merge Pull Request
        if: env.should_merge == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: "squash"
            });            
