name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Add TechnologyEnhancedLearning as nuget package source
        run: dotnet nuget add source https://pkgs.dev.azure.com/e-LfH/_packaging/LearningHubFeed/nuget/v3/index.json --name TechnologyEnhancedLearning --username 'kevin.whittaker' --password ${{ secrets.AZURE_DEVOPS_PAT }} --store-password-in-clear-text

      - name: Dotnet test
        run: dotnet test DigitalLearningSolutions.Web.Tests

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Typescript install
        run: yarn install --network-timeout 600000 --frozen-lockfile
        working-directory: ./DigitalLearningSolutions.Web
     
